### ISSUE TITLE
Circuit Diagram Request 

### ISSUE THREAD

**Issue by star210** [RoelKroes/WSPR_HAB_tracker#1]
Hi Roel

Would you share the circuit diagram? From what ive read the SI5351 needs an RF output filter and the information is murky.

Do you use the SI5351 breakout module or your own circuit?

Thanks
Star

**Comment by RoelKroes** [comment]
Hi Star,

For HAB use, the breakout modules are pretty useless as these boards do not contain a TCXO which will cause trouble with large temperature differences. The WSPR band is only 200Hz wide :-).

So I created my own circuit:  [Arduino WSPR tracker Version 5.pdf]

(https://github.com/RoelKroes/WSPR_HAB_tracker/files/10673838/Arduino.WSPR.tracker.Version.5.pdf)

Over time I changed from a 25MHz TCXO to a 27MHz TCXO as 25MHz interfered with the on board GPS.

Roel.
